### PR TITLE
Add work product - Debian Advocacy for Sugar

### PR DESCRIPTION
**Pull request by shaansubbaiah**
Please let me know if any changes are required.

### CODE REVIEW

**Comment by shaansubbaiah** [comment]
Forgot to mention that Sugar [#931](https://github.com/sugarlabs/sugar/issues/931) has not been fixed. #c104859 fixes that.

**Comment by Saumya-Mishra9129** [comment]
> temporarily hosted this file at https://github.com/shaansubbaiah/Sugar-Useful-Info/blob/master/work-done.md as previewing the commit diff is somewhat difficult.

previewed looks good. :smiley:

**Comment by JuiP** [comment]
Great! :smile:

**Comment by chimosky** [comment]
Reviewed, looks good.

Your tutorial on installing sugar on debian should be included in sugar-docs just incase anyone needs it.

**Comment by shaansubbaiah** [comment]
> 
> 
> Reviewed, looks good.
> 
> Your tutorial on installing sugar on debian should be included in sugar-docs just incase anyone needs it.

Thank you, I'll create a PR in sugar-docs.

**Comment by shaansubbaiah** [comment]
@quozl @chimosky kindly merge if there aren't any issues. Need the link to complete the final evaluation.

**Comment by chimosky** [comment]
Reviewed, I'll wait for your mentor to merge when they're satisfied.
If they don't, I'll merge later during the day as I understand today's the deadline to submit your final evaluations.

**Comment by shaansubbaiah** [comment]
@chimosky there are only a few hours left, can you do it now? @quozl is away, I'll make any changes required when he's back?

**Comment by Saumya-Mishra9129** [comment]
> @chimosky there are only a few hours left, can you do it now? @quozl is away, I'll make any changes required when he's back?

@shaansubbaiah Same problem I am facing. I made a public GitHub gist of my readme and put the link of  gist there for evaluation . https://gist.github.com/Saumya-Mishra9129/2a30c67731a07cdc9c2996e14ff8ab69. As it is also recommended in guidelines(https://developers.google.com/open-source/gsoc/help/work-product). Or you can use link of your cloned repo.

**Comment by shaansubbaiah** [comment]
> @shaansubbaiah Same problem I am facing. I made a public GitHub gist of my readme and put the link of gist there for evaluation . [gist.github.com/Saumya-Mishra9129/2a30c67731a07cdc9c2996e14ff8ab69](https://gist.github.com/Saumya-Mishra9129/2a30c67731a07cdc9c2996e14ff8ab69). As it is also recommended in guidelines([developers.google.com/open-source/gsoc/help/work-product](https://developers.google.com/open-source/gsoc/help/work-product)). Or you can use link of your cloned repo.

Thanks for the tip! Was planning of doing the same. Makes sense, as we can always add it this repo later.

**Comment by chimosky** [comment]
@shaansubbaiah I apologize for the delay.

**Comment by quozl** [comment]
Thanks.  Reviewed.  Approved.  Yes, I'm traveling, in-country, with appointments, so my usual capacity is reduced.  Sorry.

**Pull request merged**
