### PR TITLE
Add me as a mentor

### PR DESCRIPTION
**Pull request by perriefidelis**
If we can't have any coding mentors for the: Human Interface Guidelines Redesign for Sugar idea, It's fine to let it go. I think it's an interesting project.

### CODE REVIEW

**Comment by chimosky** [comment]
I've added myself as a mentor, I think this is a good idea too. @JuiP @llaske kindly review.

**Comment by srevinsaju** [comment]
> Sure! I'll merge....
> 
> > If we can't have any coding mentors for the: Human Interface Guidelines Redesign for Sugar idea, It's fine to let it go. I think it's an interesting project.
> 
> `Port ASLOv1 to PHP8` is in a similar situation.... I have no experience with PHP8 so I can't volunteer to mentor. @srevinsaju would you like to take this up?

Sure, I dont have experience with PHP8 either. If no one wants to mentor that task, I can take it up :rocket: .

**Comment by JuiP** [comment]
> Sure, I dont have experience with PHP8 either. If no one wants to mentor that task, I can take it up 🚀 .

Great! 😄 
@srevinsaju Just to be sure, do fulfill the age requirements for a mentor? The website mentions: `To participate in the Program, a Mentor must: upon registration for the Program, be eighteen (18) years of age or older.`

**Comment by srevinsaju** [comment]
Yes

**Pull request merged**
