### PR TITLE
Remove details not required in a proposal

### PR DESCRIPTION
**Pull request by pro-panda**

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@pro-panda spent a considerable amount of time writing  Your motivation and Sugar labs' motivation. Do I need to delete it from my proposal now? :sweat_smile:

**Comment by NikhilM98** [comment]
@Aniket21mathur Agreed

**Comment by pro-panda** [comment]
@aniket21mathur, I don't think these sections add value to a proposal. What matters to me is the description of the project and the timeline.

I'll wait for other's to review.

PS, if one has to spend time thinking about his motivation to work, then I would presume they're making those reasons up ;-)

**Comment by quozl** [comment]
Interesting, thanks.  I agree with the changes.  But I'll wait for @walterbender to answer.

For me;

* description of the project doesn't matter if it is the same as the project idea, but does matter if it shows a deeper understanding of the project idea than we had published, or if it breaks it down into smaller components for implementation,
* timeline doesn't matter, except inasmuch as it may show gaps in dates where a student won't be working,
* evidence of prior work matters, especially in the technical skills that the project needs, or some other self-assessment of capacity to work,
* anything about motivation is uninteresting, reminds me of management-speak, by the PHB in Dilbert cartoons, :grin:

https://google.github.io/gsocguides/student/writing-a-proposal is what Google Summer of Code provide for writing a proposal.  I'll be very interested to see any proposals which go beyond our template or project ideas.

**Comment by walterbender** [comment]
I think we can mark the motivational bits as optional. But I think it is good to give people a change to tell us where they are coming from. The timeline is important when it comes down to actually accepting a proposal and it often reveals the degree of understanding of the problem by the student. I think it is also required by Google.

**Comment by quozl** [comment]
Thanks.  Regarding timeline, I couldn't find where it is required by Google.  Perhaps they removed it.  It is useful for assessing a student's degree of understanding of the size of a project, but I feel it is secondary to evidence of capacity to do the work.

**Comment by pro-panda** [comment]
I've added the option for students to add sections which they feel are important

**Comment by Aniket21mathur** [comment]
Thanks @pro-panda .

**Pull request merged**
