### PR TITLE
Update Ideas-2019.md

### PR DESCRIPTION
**Pull request by ritwikagarwal**

### CODE REVIEW

**Comment by quozl** [comment]
@llaske, do you approve @ritwikagarwal as a coding mentor on the _Improve Sugarizer Server Dashboard_ idea?  I could not find any evidence of _demonstrated coding ability in the form of contributions of code to Sugar Labs_.

**Comment by llaske** [comment]
@quozl I don't. Never heard of him.

**Comment by quozl** [comment]
@llaske, thanks.

@ritwikagarwal, please adjust your pull request accordingly.

**Comment by Aniket21mathur** [comment]
Thanks. Reviewed. 
    * your commit messages do not provide much information, please see our [guide to commit messages](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits),

**Comment by quozl** [comment]
Thanks.  Will squash and rewrite commit message.

**Pull request merged**
