### PR TITLE
Added name as a mentor

### PR DESCRIPTION
**Pull request by vaibhavdaren**
added name as a mentor in:-
1. Export Music Blocks code to JavaScript
2. Expand Sugarizer Exerciser activity
3. Write activity for Sugarizer

### CODE REVIEW

**Comment by llaske** [comment]
@vaibhavdaren Could you explain what let you think that you could be mentor on Sugarizer ideas? I don't remember you've already contributed on Sugarizer project.

**Comment by quozl** [comment]
@llaske, my review was assessment of _demonstrated coding ability_, based on [contributions to Turtle Blocks JS for past year](https://github.com/pulls?utf8=%E2%9C%93&q=org%3Asugarlabs+is%3Apr+author%3Avaibhavdaren+archived%3Afalse+).

@vaibhavdaren, please do contribute to Sugarizer.

**Comment by llaske** [comment]
@quozl not agree. It's not significative JavaScript contributions. Note also that Turtle Blocks JS do not rely on Sugar-Web so it's very different from a "standard" Sugarizer activities.
@vaibhavdaren On Sugarizer ideas, to be able to mentor a student and help him it's important to demonstrate capacity to develop a full Sugarizer activity by yourself. Plus, knowledge on ReactJS is a prerequisite regarding for Exerciser activity.

**Comment by vaibhavdaren** [comment]
@quozl  Done. I will increase my contribution to Sugarizer development. #39 

@llaske  yes you are correct. Changes made btw I am comfortable with C++, python, javascript and angular.

Successful Completion of the project is the main priority.So, it is better that more experienced mentors are assigned

**Pull request merged**
