### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Tushar98644**
updated the year from `2021` to `2023`

### CODE REVIEW

**Comment by chimosky** [comment]
Closing this as the orgs for this year hasn't been announced yet and that change is only valid after Sugar Labs has been announced as a participating org.

**Comment by Tushar98644** [comment]
> Closing this as the orgs for this year haven't been announced yet and that change is only valid after Sugar Labs has been announced as a participating org.

The organizations have already been announced for Gsoc2023...pls verify from your side

**Comment by quozl** [comment]
https://summerofcode.withgoogle.com/programs/2023/organizations does list Sugar Labs.  Next step is for Sugar Labs to decide to proceed.

**Comment by chimosky** [comment]
True, just seeing that the timeline for org announcement was yestereday.

**Comment by Tushar98644** [comment]
> True, just seeing that the timeline for org announcement was yestereday. Thanks for pointing that out.

pleasure....I would like to discuss the 'Maintain Port Sugar Activities to Flatpak' idea with you....where shall i ping you?

**Pull request merged**
