### PR TITLE
GSoC work-product submission

### PR DESCRIPTION
**Pull request by JuiP**
@quozl @chimosky @walterbender @srevinsaju Please review and suggest changes.

### CODE REVIEW

**Comment by srevinsaju** [comment]
Nice :+1:

**Comment by Saumya-Mishra9129** [comment]
Nice work @JuiP :smile:

**Comment by quozl** [comment]
Thanks.  Reviewed.  I suggest;
* add your name (yes, it is in the file name, but it isn't obvious there),
* add selected other details about you that were in your proposal,
* confirm you are only linking "some" and not "all" of the commits, and if you have to only link "some" then explain why not "all",
* make the links to commit in each table cell into a list within the table cell; the comma separated list is hard to parse.

**Comment by shaansubbaiah** [comment]
Great work 👍

**Pull request merged**
