### PR TITLE
Sparsh Goenka student report.

### PR DESCRIPTION
**Pull request by sparshg**
@chimosky @srevinsaju @quozl 
Please review the draft I wrote for my final submission.

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.

**Comment by sparshg** [comment]
@chimosky @srevinsaju @quozl Can we merge this PR, I need to give a public link of my work in two days.

**Comment by quozl** [comment]
You can probably give a link to the pull request.

I'll wait for your mentors to merge it.  If they delay, ask them about it.

**Comment by chimosky** [comment]
Reviewed, thanks for your work!

**Pull request merged**
