### PR TITLE
Add assisting mentor

### PR DESCRIPTION
**Pull request by srevinsaju**
If it seems appropriate :)

### CODE REVIEW

**Comment by quozl** [comment]
That would be good.  You do meet the knowledge criteria!  Please confirm you meet the minimum age criteria, see [the rules](https://summerofcode.withgoogle.com/rules/).  If not, you can still participate as a community member through GitHub, mailing list, etc.

**Comment by srevinsaju** [comment]
I hadn't read the rules, sorry about that. I am underage.

**Comment by quozl** [comment]
Looking forward to see that.  We've seen this before; underage developer ends up teaching those university students a lot.  :grin:

**Comment by srevinsaju** [comment]
Thanks @quozl, inspiring indeed :)

**Pull request closed without merging**
