### PR TITLE
Sakshii rk patch 1

### PR DESCRIPTION
**Pull request by SakshiiRK**

### CODE REVIEW

**Comment by chimosky** [comment]
Looks like spam to me as they haven't made any effort to use our software and just want to add an idea. Closing this.

**Comment by SakshiiRK** [comment]
> Thanks.  Missing is impact on software for elementary-age school children, which has been our main focus.  I hope you haven't got an idea for which you are looking for people to help fund it, but rather know us and are looking for ideas that will help us.

What should I do

**Comment by quozl** [comment]
Sorry, that's not for me to say.

**Comment by chimosky** [comment]
> > Thanks.  Missing is impact on software for elementary-age school children, which has been our main focus.  I hope you haven't got an idea for which you are looking for people to help fund it, but rather know us and are looking for ideas that will help us.
> 
> What should I do

I'll suggest you use any of our software, fix bugs you notice and can fix, or open issues for the ones you don't intend to fix.
Our [docs](https://github.com/sugarlabs/sugar-docs) is a great place to start.

**Pull request closed without merging**
