### PR TITLE
GSoC submission by Hrishi Patel

### PR DESCRIPTION
**Pull request by Hrishi1999**
Final submission for GSoC 2019. Please review and merge as soon as possible so I can complete my final evaluation. Thanks!

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@Hrishi1999 should we give a link to our own branch for the evaluation?

**Comment by Hrishi1999** [comment]
Some of my commits are from my feature branches. You can link it if you want to, but it shouldn't be confusing to the reader.

**Comment by pro-panda** [comment]
@Hrishi1999, update your file path to `archives/2019/student-reports/<project-name>-<student-name>.md`

**Comment by Hrishi1999** [comment]
@pro-panda Done!

**Comment by pro-panda** [comment]
@Hrishi1999, Thanks.
I'll wait for your mentors to review this PR.

**Comment by samswag** [comment]
@pro-panda You have a +1 from me.

**Comment by Hrishi1999** [comment]
Thanks @samswag @pro-panda

**Pull request merged**
