### PR TITLE
Add a new GSoC task

### PR DESCRIPTION
**Pull request by perriefidelis**
The goal of this task is to build a better version of the current website (https://sugarlabs.org/)  with a great focus on code reusability, brilliant user experience, web accessibility, optimization, and code testing. However, after the new website have been developed, the student will be required to conduct A/B testing and analyze the performance of both websites. 

The student will also be required to restructure the current display structure of the Sugar Labs Wiki Page (https://wiki.sugarlabs.org/go/Welcome_to_the_Sugar_Labs_wiki), making it more accessible and with a good looking interface.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Nice looking project idea.  However, my vote is no, because the project idea;
* is not coding of or for our open source software products (Sugarizer, Sugar, and Music Blocks),
* has no coding mentor,
* doesn't list assisting mentors that have demonstrated new learning in the technologies and tools needed; the discussion on the GSoC mentors mailing list in the past few days about mentors needing technical skills reminds us of the importance of this,
* has been tried before; that's how we ended up with what we have now,
* is too ambitious in scope; static HTML would be enough for our purpose to inform our current and potential stakeholders,
* requires extensive community consultation that will prevent the student from moving forward; or if consultation is skipped as happened before will result in a web site that meets few of our needs,
* doesn't address the fundamental workflow issues with our web sites; that the content is out of date, and unmaintained, and there have been no significant updates to content except where the responsible maintainers (Lionel, Walter, and myself) have taken action.

Here's how to move the project idea forward, outside the context of GSoC;
* concentrate on the updating of content, the way in which the responsible maintainers and others in Sugar Labs can produce content, and rewards for producing content,
* use a standard maintained theme without any changes, such as Jekyll,
* begin to iterate immediately, don't wait for student resources; there's real content that can be updated now,
* have approval and buy-in from all three software maintainers.

**Comment by chimosky** [comment]
> * is not coding of or for our open source software products (Sugarizer, Sugar, and Music Blocks),

A website is a crucial part of any organization. 

> * doesn't address the fundamental workflow issues with our web sites; that the content is out of date, and unmaintained, and there have been no significant updates to content except where the responsible maintainers (Lionel, Walter, and myself) have taken action.

I agree with you and this is also where I have issues.

This task from what I've seen aims to also implement the A/B testing that was decided quite a while ago to be implemented but never took off, GSoC is a great place to do this because at the moment no one will dedicate their time to implementing this kind of work for no fee.

Lack of maintenance is the only issue I see here.

**Comment by ritjoe** [comment]
On Thu, Mar 12, 2020 at 05:56:42PM -0700, Ibiam Chihurumnaya wrote:
>       □ is not coding of or for our open source software products (Sugarizer,
>         Sugar, and Music Blocks),
> 
> A website is a crucial part of any organization.

As best I can tell, noting that they are non-coding is not meant to reflect on their 
overall value, but on how well they meet GSoC requirements. 

Please see this thread:

http://lists.sugarlabs.org/archive/sugar-devel/2018-February/055009.html

**Comment by chimosky** [comment]
> On Thu, Mar 12, 2020 at 05:56:42PM -0700, Ibiam Chihurumnaya wrote: □ is not coding of or for our open source software products (Sugarizer, Sugar, and Music Blocks), A website is a crucial part of any organization.
> As best I can tell, noting that they are non-coding is not meant to reflect on their overall value, but on how well they meet GSoC requirements. Please see this thread: http://lists.sugarlabs.org/archive/sugar-devel/2018-February/055009.html

The website comes under coding, @quozl's complaint is that it's not one of our open source software products.

**Comment by quozl** [comment]
Yes, that's right Joe.  We need a web site.  We need updated content on the web site.  We don't need twelve weeks of full time coding to make a web site.  Therefore we can't make this a GSoC project idea without somehow (a) leaving out the content maintenance and appearance, and (b) increasing the amount of coding.  A/B testing is more of an administrative process than coding.  I'll be happy to review the project idea more fully once the coding burden reaches about twelve weeks full time work.  But even if that happens, we won't have the content maintenance and appearance sorted out, and we tried that before in the last rewrite; it doesn't work.

**Comment by akhilarya123** [comment]
Hello everyone , I am new here . Can anybody help me on how to begin as I can't see any  open issues . Even a small help will be highly appreciable .

**Comment by quozl** [comment]
Thanks for asking.  Yes, there are no open issues here.  Our habit is to open an issue when (a) something needs to be changed, (b) we don't know how to do it, (c) we can't guide anyone how to do it, (d) we don't have the time to do it or learn how to do it ourselves.  An issue is effectively an invitation to use your self-directed capacity to figure out what to do.  But you don't need an invitation to use your head.  You can use it without invitation.  Hope that helps!

**Comment by JuiP** [comment]
@quozl @chimosky @perriefidelis Judging from [this comment](https://github.com/sugarlabs/GSoC/pull/91#issuecomment-598965914), can we modify this idea to fit the reduced time commitment? If yes would you, @perriefidelis like to modify it or is this pull request stale/irrelevant?

**Comment by quozl** [comment]
No thanks.  I stand by my [original comments](https://github.com/sugarlabs/GSoC/pull/91#issuecomment-598433363) that this is not a suitable task for a student.  The reduced time available in GSoC 2021 doesn't change that.

**Comment by chimosky** [comment]
> @quozl @chimosky @perriefidelis Judging from [this comment](https://github.com/sugarlabs/GSoC/pull/91#issuecomment-598965914), can we modify this idea to fit the reduced time commitment? If yes would you, @perriefidelis like to modify it or is this pull request stale/irrelevant?

It'll be good to add it with another project, say the idea on porting [aslo-v1 to PHP8](https://github.com/sugarlabs/GSoC/pull/115).

**Comment by perriefidelis** [comment]
If this can be added to another project to solve the issue of timeframe, I'll do some modification to the idea and repropose it.

**Comment by quozl** [comment]
Timeframe is not an issue of significance.  I don't think adding to another GSoC project would help.

My reasons for not agreeing to change the web site as part of a GSoC project are;
* it is not coding of or for our open source software products (Sugarizer, Sugar, and Music Blocks),
* has been tried before; that's how we ended up with what we have now,
* requires extensive community consultation that will prevent the student from moving forward; or if consultation is skipped as happened before will result in a web site that meets few of our needs,
* doesn't address the fundamental workflow issues with our web sites; that the content is out of date, and unmaintained, and there have been no significant updates to content except where the responsible maintainers (Lionel, Walter, and myself) have taken action.

Here's how to move the web site forward, outside the context of GSoC;
* concentrate on the updating of content, the way in which the responsible maintainers and others in Sugar Labs can produce content, and rewards for producing content,
* use a standard maintained theme without any changes, such as Jekyll,
* begin to iterate immediately, don't wait for student resources; there's real content that can be updated now,
* have approval and buy-in from all three software maintainers.

**Comment by quozl** [comment]
> Here's how to move the web site forward, outside the context of GSoC;
> 
>     * concentrate on the updating of content, the way in which the responsible maintainers and others in Sugar Labs can produce content, and rewards for producing content,
> 
>     * use a standard maintained theme without any changes, such as Jekyll,
> 
>     * begin to iterate immediately, don't wait for student resources; there's real content that can be updated now,
> 
>     * have approval and buy-in from all three software maintainers.

As nothing has happened on this, I presume nobody is available to help, and that our three software maintainers remain responsible for updating the content.  It is a bit alarming to think we have people willing to mentor a student to make a web site yet are unable to afford the time to work on the problem outside the context of GSoC.

**Pull request closed without merging**
