### PR TITLE
added myself mentor

### PR DESCRIPTION
**Pull request by vaibhavdaren**
for music blocks project.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  We are obligated to provide experienced mentors.

Other coding mentors I've approved because I found a clear history of commits to Music Blocks, but I can't find any for you.  Your own musicblocks fork is 2463 commits behind sugarlabs:master.  https://github.com/sugarlabs/musicblocks/issues/1886 and https://github.com/sugarlabs/musicblocks/pull/1996 were your most recent involvement.

So I'll punt to the experts.  @fakela, @walterbender, please review and approve?

**Comment by walterbender** [comment]
Vaibhav;s commits were to Turtle Blocks JS.

**Comment by quozl** [comment]
Thanks.  I see them now.  Do you approve adding?

**Comment by walterbender** [comment]
Yes.

**Comment by quozl** [comment]
Thanks.  Merged.

**Pull request closed without merging**
