### PR TITLE
GSoC for Sugarizer Science

### PR DESCRIPTION
**Pull request by iqraceme**
A proposal for a Sugarizer collection of tools useful for students "doing Science"

### CODE REVIEW

**Comment by quozl** [comment]
Thanks, that's interesting.

@iqraceme, https://github.com/sugarlabs/sugarizer/tree/iqraceme/primero commits hasn't moved since October, yet a new release of Sugarizer was made.  Do you plan to maintain Primero?

@llaske, can you please advise the status of the earlier Primero work in relation to Sugarizer?  Was it merged?  Having a multitude of Sugarizer forks will quickly become unmanageable, especially as changes to Sugarizer won't be reflected in the forks.  How do you think this idea might be made acceptable for merging?  Can Sugarizer be changed to support activity collections?

@samswag, this is entirely my opinion, but you haven't much of _a demonstrated coding ability in the form of contributions of code to Sugar Labs_.  One pull request for Browse in the last week doesn't fix this.  Ten commits to Sugarizer or Music Blocks would.  So I'd like to see you in there as an _assistant mentor_.  I'm sure you can still answer coding questions if you like, but I don't think Sugar Labs should claim that you will handle it, given there's so little public evidence in our repositories.

**Comment by samswag** [comment]
@quozl you have my consent to change from coding to assistant. @iqraceme I think you need make the switch.

**Comment by quozl** [comment]
@samswag, thanks.  Yes, best if @iqraceme makes an additional commit and pushes it.

**Comment by iqraceme** [comment]
@quozl, I will take out time to maintain Primero. Yeah, let me fix this conflict in the Ideas-2019.md file. I will also change @samswag from coding to assistant.

**Comment by llaske** [comment]
Create a dedicated package of Sugarizer with a specific activities do not require a GSoC project. It's just a settings change in activities directory and activities.json file (see https://github.com/llaske/sugarizer/tree/dev#activities for more) then rebuild Sugarizer for each platform.

Regarding Sugarizer Primero, I'm afraid upgrading to the latest Sugarizer version will be complex. AFAK Sugarizer Primero was forked from the master branch of v0.9 so it's 3 version behind the latest version. Plus, Sugarizer Primero replaced existing sources files, image and CSS of Sugarizer without identified it and without conditional testing (i.e. "if (SugarizerPrimero) do this else do that") so it will be complex to reinject code.

**Comment by quozl** [comment]
@llaske, thanks.

**Comment by llaske** [comment]
Yes, Get Things Done is already in Sugarizer https://github.com/llaske/sugarizer/tree/dev/activities/GetThingsDone.activity

**Comment by GrannieB** [comment]
Yes, Sugarizer Science would be, and Primero1° is, a fork of Sugarizer. But, a lot of effort was made to insure language independence, including field testing with young children. We would propose to do field testing again with Sugarizer Science.

Originally, we intended that Primero1° be called just that, without the Sugarizer name attached. Sugarizer would be mentioned in the description in the App store and people would be referred to it if they wanted more Activities. The same thing could be done with Sugarizer Science, we could just call it "Science Tools" or something like that.

We did intend to include an entirely new Activity in Primero1°, MathStiks (sort of virtual cuisenaire rods), which, hopefully can be completed sometime this year. The 12 week timeline was filled up fully and even had to be revised when some things took longer than expected or the lack of tools needed (eg access to a Mac for an iOS version) required a change in the schedule. 

This very similar proposal would certainly take the 12 weeks allotted, especially if you consider the time needed to field test it with real children to make sure it is appropriate, easy to use and language independent and to incorporate any needed changes as we did with Primero1° last summer.

Maybe we should just call it **Science Tools** and in the description note that it comes from Sugarizer and Sugar. There are at least 4 other Sugar Activities that could be included that are not in Sugarizer... Weather, Panorama, Poll, and, maybe, Timeline. I need to communicate with Rosamel Ramirez to see if there is something else that it would be nice to include. She was using a graphing Activity when we visited her class in Uruguay that would be perfect to include as a science tool.

I see Primero1° and this Science Tools App as kind of "stealth" marketing tools for Sugarizer. You can bring in the user with these and encourage them to explore the entire Sugarizer App if they like these.

**Comment by llaske** [comment]
For me it doesn't mind if "Sugarizer" is not in the name of "Primero1°" and/or is not in the name of the new "Science" tool. Sugarizer is an open source software with a very permissive Apache 2 license so you're absolutely free to do what you want. I'm fine with that.

BTW the main difficulty in software is not development it's maintenance. We're in trouble in SugarLabs because lot of Sugar activities has been abandoned by their original developers so these activities no longer works due to system updates (Ubuntu, Gtk3, ...). My concern is that Primero is 4 versions below the current Sugarizer branch and it means that it could just stop working because a future browser version or a future Android version will be incompatible with it. And if it happens nobody will be able to fix it because it's not linked to the latest Sugarizer branch. Unfortunately, it's how thinks works in software world. Giving a software without maintenance is like giving a car without gaz, it's not fun during a long time 😄 

Regarding GSoC, we're speaking of 12 weeks of full-time development. I don't think field testing could be considered in this time, it's the job of mentor, not the student job. Like @quozl , in the current description I see only packaging and it's not enough work for a full GSoC project.

**Comment by quozl** [comment]
@llaske, thanks for your thoughts.  I agree, this task does not seem to be 12 weeks of full-time development, as it stands as https://github.com/sugarlabs/GSoC/pull/33/commits/7ead1fbabd035f9014f8ec2bfdc1e783239d389c.  It could be done in a few hours by an average coder with a few months of JavaScript experience.

@GrannieB wrote:
> The 12 week timeline was filled up fully and even had to be revised when some things took longer than expected or the lack of tools needed (eg access to a Mac for an iOS version) required a change in the schedule.

That's unfair.  @iqraceme wasn't given any significant coding mentor supervision during Primero; as far as I can see, her mentors were not active developers at Sugar Labs.  She performed reasonably well despite this, but created something that is less maintainable.  I'm very ashamed of how Sugar Labs has failed her.

@llaske, you might do it in half an hour; you already know more than anybody else does about Sugarizer, and you have access to all the tools needed to make a release.  You're the best person for the job.  If you do it now, you will entirely obviate the need for a project, and we can all go on to doing something else.  How about it?

Alternatively, would you be willing to be a coding mentor for this task, once it has enough work in it to fill the 12 weeks?

**Comment by iqraceme** [comment]
This project idea can be dropped because as per the discussion, the scope of this project is infeasible. Otherwise, someone may propose an entirely new science based sugarizer activity for sugarizer (That is already added as an idea in Ideas list)

**Comment by llaske** [comment]
@quozl Sure I'm agree to help to produce a Sugarizer Science package and I can help on mentoring too thought I can't be mentor myself on it because I'm already mentor/co-mentor on 3 others ideas...

**Comment by quozl** [comment]
Thanks everyone for your opinions.  I'll close this now.

* @pro-panda let's add JavaScript into [Create a new set of activities](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2019.md#create-a-new-set-of-activities) since that's the best way to make sure any new Science activities will be compatible with both Sugar and Sugarizer; please review https://github.com/sugarlabs/GSoC/pull/36,

* then Sugarizer activities for Science; can be added to [Create a new set of activities](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2019.md#create-a-new-set-of-activities) so for @GrannieB, @iqraceme, @samswag and @llaske your next actions are to add yourself as assistant mentor and guide the prospective students when they begin to post on sugar-devel@,

* Sugarizer Science package; @GrannieB, @iqraceme, @samswag and @llaske can work together on this idea subject to their availability,

* Primero will be maintained subject to availability of @iqraceme.

**Comment by GrannieB** [comment]
James... that sounds wonderful! As a retired secondary school science teacher, I would like to take the lead in choosing and directing content for this project as much as possible. My vision is that the purpose of Sugarizer Science would not be to learn "about science," but to give users some tools they can use to actually "do" science. I can see, in my imagination, children all over the world carrying tablets and hand-me-down used smart phones, and using them to measure, record, tabulate and learn about their world and the universe. At this moment there don't seem to be any dedicated Apps to do this so a real niche could be filled. Count me in as a co-mentor if a prospective intern wants to tackle this project. I enjoyed working with Samson and Iqra last summer and would love to work with them and with Lionel as well. So... count me in!

**Comment by iqraceme** [comment]
I am willing to be a co-mentor for sugarizer science

**Pull request closed without merging**
