### PR TITLE
Add Design improvements for key/mode

### PR DESCRIPTION
**Pull request by pikurasa**

### CODE REVIEW

**Comment by quozl** [comment]
@walterbender, please review.  Can this project idea fill 12 weeks of full time equivalent for a new programmer?

**Comment by walterbender** [comment]
I think that the implications from this project spill over into almost every corner of music blocks: for example, which keys are made available in the music keyboard. So, yes, I think there is 12 weeks of work here by the right student.

**Comment by quozl** [comment]
Reviewed.  Added changes.  Please review;

https://github.com/sugarlabs/GSoC/blob/b953cfd2aa424fbb498db4d12368756e0ee66551/Ideas-2020.md#music-blocks-scale-degree-vs-nth-modal-pitch

**Comment by pikurasa** [comment]
Changes look good to me.

Thanks!

**Pull request merged**
