### PR TITLE
GSoC21: idea for porting aslo-v1 to php8

### LINKED ISSUE #113: Suggestion for GSoC 2021: Port ASLOv1 to PHP 7 or 8
It would be nice to have this migrated to a newer PHP version, which would help us upgrade some infrastructure. 

Please feel free to close this issue / edit this issue if it seems inappropriate for GSoC

### PR DESCRIPTION
**Pull request by srevinsaju**
Closes #113 

Needs review,

### CODE REVIEW

**Comment by quozl** [comment]
Looks good.  There are also some [issues](https://github.com/sugarlabs/aslo/issues) that may be suitable for any student wishing to stake their claim in the community.

**Comment by srevinsaju** [comment]
> Looks good. There are also some [issues](https://github.com/sugarlabs/aslo/issues) that may be suitable for any student wishing to stake their claim in the community.

Agreed, I will add some important issues to the `Suggested Issues` section

**Comment by quozl** [comment]
Thanks for progressing this.  Deadline is Friday, Feb 19th at 1900 UTC.

**Comment by srevinsaju** [comment]
Thanks for the heads up.

**Comment by quozl** [comment]
Reviewed.  Would you like to rebase?

**Comment by JuiP** [comment]
ping @srevinsaju

**Comment by srevinsaju** [comment]
Thanks, was caught up with some school work. will rebase.

**Comment by srevinsaju** [comment]
Rebased, fixed conflicts. Feel free to squash.

**Comment by JuiP** [comment]
Thanks; merged! :smile:

**Pull request merged**
