### PR TITLE
Mentor requisition - 'Improve and maintain 12 or 6 Sugar activities'

### PR DESCRIPTION
**Pull request by sourabhaa**
I'd like to participate in GSoC'23 as a mentor for the projects 'Improve and maintain 12 Sugar activities' and 'Improve and maintain 6 Sugar activities'. After the exciting journey as a student in GSoC 2021 and 2022, I'm interested to be a mentor for the same project this summer.

Requesting the org admins to kindly approve.

### CODE REVIEW

**Comment by quozl** [comment]
Yay.

Also check that you have applied for membership of Sugar Labs.

**Comment by sourabhaa** [comment]
Thanks @quozl. I went through the instructions to [apply for membership](https://wiki.sugarlabs.org/go/Sugar_Labs/Members), I'm not sure if I've to send the application mail to any of the members with sugarlab.org mail or to is there a mailing list that includes all the members?

**Comment by quozl** [comment]
That's great.  I haven't seen it yet though.  Send to members@sugarlabs.org as the instructions say.  That is an alias for @aperezbios, @quozl, and @chimosky.

**Comment by sourabhaa** [comment]
thanks!

**Pull request closed without merging**
